// <auto-generated />
namespace My_Follow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes322 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes322));
        
        string IMigrationMetadata.Id
        {
            get { return "201510220920304_changes322"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
